# Progetto IUM - Data Analysis
## Università di Informatica, Unito
Gruppo Federico Raso, Federico Verra

## Analizzo e pulisco i dati

In [3]:
import numpy
import pandas as pd
import plotly.express as px
print(numpy.__version__)

2.1.3


In [4]:
data_directory = "./data/"
actors_df = pd.read_csv(data_directory+'actors.csv')
countries_df = pd.read_csv(data_directory+'countries.csv')
crew_df = pd.read_csv(data_directory+'crew.csv')
genres_df = pd.read_csv(data_directory+'genres.csv')
languages_df = pd.read_csv(data_directory+'languages.csv')
movies_df = pd.read_csv(data_directory+'movies.csv')
posters_df = pd.read_csv(data_directory+'posters.csv')
releases_df = pd.read_csv(data_directory+'releases.csv')
reviews_rotten_df = pd.read_csv(data_directory+'rotten_tomatoes_reviews.csv')
studios_df = pd.read_csv(data_directory+'studios.csv')
oscar_df = pd.read_csv(data_directory+'the_oscar_awards.csv')
reviews_rotten_df

rotten_tomatoes_link  \
0                  m/0814255   
1                  m/0814255   
2                  m/0814255   
3                  m/0814255   
4                  m/0814255   
...                      ...   
1129882          m/zulu_dawn   
1129883          m/zulu_dawn   
1129884          m/zulu_dawn   
1129885          m/zulu_dawn   
1129886          m/zulu_dawn   

                                               movie_title        critic_name  \
0        Percy Jackson & the Olympians: The Lightning T...    Andrew L. Urban   
1        Percy Jackson & the Olympians: The Lightning T...      Louise Keller   
2        Percy Jackson & the Olympians: The Lightning T...                NaN   
3        Percy Jackson & the Olympians: The Lightning T...       Ben McEachen   
4        Percy Jackson & the Olympians: The Lightning T...        Ethan Alter   
...                                                    ...                ...   
1129882                                          Zulu Dawn      Chuck O'Leary   
1129883                                          Zulu Dawn          Ken Hanke   
1129884                                          Zulu Dawn    Dennis Schwartz   
1129885                                          Zulu Dawn  Christopher Lloyd   
1129886                                          Zulu Dawn     Brent McKnight   

         top_critic                   publisher_name review_type review_score  \
0             False                   Urban Cinefile       Fresh          NaN   
1             False                   Urban Cinefile       Fresh          NaN   
2             False              FILMINK (Australia)       Fresh          NaN   
3             False          Sunday Mail (Australia)       Fresh        3.5/5   
4              True               Hollywood Reporter      Rotten          NaN   
...             ...                              ...         ...          ...   
1129882       False                 Fantastica Daily      Rotten          2/5   
1129883       False  Mountain Xpress (Asheville, NC)       Fresh        3.5/5   
1129884       False    Dennis Schwartz Movie Reviews       Fresh           B+   
1129885       False          Sarasota Herald-Tribune      Rotten        3.5/5   
1129886       False             The Last Thing I See      Rotten            C   

        review_date                                     review_content  
0        2010-02-06  A fantasy adventure that fuses Greek mythology...  
1        2010-02-06  Uma Thurman as Medusa, the gorgon with a coiff...  
2        2010-02-09  With a top-notch cast and dazzling special eff...  
3        2010-02-09  Whether audiences will get behind The Lightnin...  
4        2010-02-10  What's really lacking in The Lightning Thief i...  
...             ...                                                ...  
1129882  2005-11-02                                                NaN  
1129883  2007-03-07  Seen today, it's not only a startling indictme...  
1129884  2010-09-16  A rousing visual spectacle that's a prequel of...  
1129885  2011-02-28  A simple two-act story: Prelude to war, and th...  
1129886  2020-07-09  Rides the line between being a pure artifact o...  

[1129887 rows x 9 columns]

## Quale paese ha vinto più oscar?

## Chi ha prodotto più film?

## La bellezza di un film, può essere influenzata dalla durata?

## Nel tempo come si è evoluta la durata media dei film?

In [48]:
time_df =movies_df[['id', 'date', 'minute']].copy()
new_names = {'date':'year','minute': 'length'}
time_df=time_df.rename(columns=new_names)
time_df.head(10)


id    year  length
0  1000001  2023.0   114.0
1  1000002  2019.0   133.0
2  1000003  2022.0   140.0
3  1000004  1999.0   139.0
4  1000005  2016.0   129.0
5  1000006  2023.0   181.0
6  1000007  2014.0   169.0
7  1000008  2019.0   122.0
8  1000009  2021.0   155.0
9  1000010  1994.0   154.0

In [56]:
time_df.dtypes

id          int64
year        int64
length    float64
dtype: object

In [52]:
time_df.dropna(axis=0, inplace=True)
print(time_df.duplicated().sum())

0


In [53]:
time_df['year'] = time_df['year'].astype(int)
time_df.dtypes


id          int64
year        int64
length    float64
dtype: object

In [63]:
time_df = time_df[time_df['length']>60]
average_length = time_df.groupby('year')['length'].mean().reset_index()
average_length.head(10)


year      length
0  1899  135.000000
1  1900   79.000000
2  1903  120.000000
3  1904   70.000000
4  1906   87.500000
5  1907  155.000000
6  1908  135.500000
7  1910   85.600000
8  1911   87.600000
9  1912   94.153846

In [64]:
average_length['year'].unique()

array([1899, 1900, 1903, 1904, 1906, 1907, 1908, 1910, 1911, 1912, 1913,
       1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924,
       1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935,
       1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946,
       1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957,
       1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968,
       1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979,
       1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990,
       1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023,
       2024, 2025, 2026, 2027, 2028, 2029, 2030])

In [65]:
average_length = average_length[average_length['year'] < 2025]
average_length['year'].unique()

array([1899, 1900, 1903, 1904, 1906, 1907, 1908, 1910, 1911, 1912, 1913,
       1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924,
       1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935,
       1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946,
       1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957,
       1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968,
       1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979,
       1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990,
       1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023,
       2024])

In [66]:
average_length['length'].unique()

array([135.        ,  79.        , 120.        ,  70.        ,
        87.5       , 155.        , 135.5       ,  85.6       ,
        87.6       ,  94.15384615,  98.16      , 113.02702703,
       110.475     , 105.39534884,  96.72560976,  96.05590062,
        94.15300546,  92.46190476,  92.24663677,  92.18518519,
        90.70671378,  86.14939024,  86.9637883 ,  85.1793722 ,
        88.30821918,  89.322     ,  86.1210084 ,  82.57461646,
        82.26593137,  81.85083532,  81.52238806,  83.25782093,
        82.91897655,  83.73855544,  85.88418933,  86.73838384,
        87.22052846,  87.63296703,  89.63856813,  89.06394708,
        89.60551559,  90.38719068,  89.61014493,  90.20663265,
        90.26564345,  90.59194777,  91.48095238,  91.88568935,
        92.39370748,  92.83817427,  93.00321027,  94.50657386,
        94.32639885,  93.4985755 ,  92.72005125,  93.52200868,
        94.49937186,  97.27020358,  94.84479718,  95.74120879,
        95.9238927 ,  98.23103448,  97.85435268,  97.09

In [2]:
fig = px.scatter(
    average_length,
    x="year",
    y="length",
    animation_frame="year",
    title="Evoluzione della lunghezza dei film negli anni",
    labels={'year': 'Anno', 'length': 'Durata (minuti)'},
    range_x=[1899, 2024],
    range_y=[60, 160]
)

fig.update_traces(marker=dict(size=15, color='blue'))
fig.update_layout(
    xaxis=dict(title="Anno"),
    yaxis=dict(title="Durata (minuti)"),
    showlegend=False
)
fig.show()

NameError: name 'px' is not defined